service_name: github
build_root: build
gcov_options: -lp
exclude_lines_pattern:
  - '.*/build/.+\.c'
exclude:
  - fuzzer 
  - fuzzing 
  - gnupg 
  - canokey-crypto 
  - virt-card 
  - u2f-ref-code 
  - tinycbor 
  - littlefs 
  - test 
  - interfaces