dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - cmake
      - psmisc
      - pcscd
      - pcsc-tools
      - yubico-piv-tool
      - gnupg2
      - scdaemon
      - opensc
      - openssl
      - libpcsclite-dev
      - libcmocka-dev

script:
  - gpg --version
  - git clone --depth 1 https://github.com/google/u2f-ref-code.git
  - pushd u2f-ref-code/u2f-tests/HID
  - git clone --depth 1 -b lollipop-release https://android.googlesource.com/platform/system/core
  - cd ../NFC
  - git apply ../../../virt-card/disable-short-apdu-test.patch
  - make
  - popd
  -
  - mkdir build && pushd build
  - cmake .. -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - ./canokey-crypto/test/test_aes
  - ./canokey-crypto/test/test_ecdsa
  - ./canokey-crypto/test/test_sha
  - ./test/test_u2f
  - ./test/test_piv
  - ./test/test_openpgp
  - popd
  -
  - sudo killall -9 pcscd || true
  - sudo cp build/libu2f-virt-card.so /usr/local/lib/
  - sudo cp pcscd-reader.conf /etc/reader.conf.d/
  - travis_wait 3 sudo pcscd -a -f >/tmp/pcscd.log &
  - sleep 3
  - timeout 1s pcsc_scan || true
  - # U2F tests:
  - echo 0 | ./u2f-ref-code/u2f-tests/NFC/u2f_nfc_test -v | tee /tmp/u2f_nfc_test.log
  - test $(grep -c 'PASS(signCheckSignature(regReq, regRsp, authReq, authRsp, rapduLen))' /tmp/u2f_nfc_test.log) -eq 3
  - # OpenPGP tests:
  - echo 12345678 >/tmp/passwd
  - "echo -e 'Key-Type: 1\\nKey-Length: 2048\\nSubkey-Type: 1\\nSubkey-Length: 2048\\nName-Real: Someone\\nName-Email: foo@example.com\\nPassphrase: 12345678\\n%commit\\n%echo done' | gpg --batch --gen-key"
  - KEYID=$(gpg -K --with-colons |grep -P '^sec'|grep -oP '\w{16}')
  - echo -e 'addkey\n6\n2048\n0\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # [2] encrypt key
  - echo -e 'addkey\n4\n2048\n0\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # [3] sign key
  - echo -e 'key 1\nkeytocard\n1\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # key[1] to Signature key
  - echo -e 'key 2\nkeytocard\n2\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # key[2] to Encryption key
  - echo -e 'key 3\nkeytocard\n3\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # key[3] to Authentication key
  - echo -e 'admin\nname\nfirstname\nlastname\nurl\nexample.com\nlogin\nmyuserid\nsex\nm\nlist\nquit' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-card
  - echo 123456 >/tmp/passwd
  - "echo hello | gpg --armor --pinentry-mode loopback --passphrase-file=/tmp/passwd --default-key $(gpg -K --with-colons|awk -F: '$1 ~ /ssb/ && $12 ~ /s/ {print $5}'|tail -n 1) -s >/tmp/sign.gpg"
  - gpg </tmp/sign.gpg
  - "echo hello2 | gpg --armor --pinentry-mode loopback --passphrase-file=/tmp/passwd --default-key $(gpg -K --with-colons|awk -F: '$1 ~ /ssb/ && $12 ~ /s/ {print $5}'|head -n 1) -s >/tmp/sign.gpg"
  - gpg </tmp/sign.gpg
  - "echo world | gpg --yes --armor --recipient $(gpg -K --with-colons | awk -F: '$1 ~ /ssb/ && $12 == \"e\" {print $5}') --encrypt >/tmp/enc.gpg"
  - gpg --pinentry-mode loopback --passphrase-file=/tmp/passwd -d /tmp/enc.gpg
  - echo 12345678 >/tmp/passwd
  - echo -e 'admin\nfactory-reset\ny\nyes' | gpg --command-fd 0 --batch --edit-card # clear all keys, no pin verification at all
  - echo -e 'addkey\n10\n3\n0\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # gen ecdsa P-256 key[4]
  - echo -e 'key 4\nkeytocard\n1\nsave' | gpg --yes --command-fd 0 --pinentry-mode loopback --passphrase-file=/tmp/passwd --batch --edit-key $KEYID # key[4] to Signature key
  - echo 123456 >/tmp/passwd
  - "echo hello3 | gpg --armor --pinentry-mode loopback --passphrase-file=/tmp/passwd --default-key $(gpg -K --with-colons|awk -F: '$1 ~ /ssb/ && $12 ~ /s/ {print $5}'|tail -n 1) -s >/tmp/sign.gpg"
  - gpg </tmp/sign.gpg
  - gpgconf --kill gpg-agent
  - # PIV tests:
  - pkcs15-tool -D
  - yubico-piv-tool -r "" -a verify-pin -P 123456
  - yubico-piv-tool -r "" -a change-pin -P 123456 -N 654321
  - yubico-piv-tool -r "" -a verify-pin -P 654321
  - yubico-piv-tool -r "" -a verify-pin -P 123456 2>&1 | grep '2 tries left before pin is blocked.'
  - yubico-piv-tool -r "" -a verify-pin -P 123456 2>&1 | grep '1 tries left before pin is blocked.'
  - yubico-piv-tool -r "" -a verify-pin -P 654321
  - yubico-piv-tool -r "" -a set-mgm-key -n 010203040506070801020304050607080102030405060708
  - yubico-piv-tool -r "" -a generate -s 9e >/tmp/pubkey-9e.pem
  - yubico-piv-tool -r "" -a selfsign-certificate -s 9e -S '/CN=CertAtSlot9e' < /tmp/pubkey-9e.pem >/tmp/cert-9e.pem
  - yubico-piv-tool -r "" -a import-certificate -s 9e < /tmp/cert-9e.pem
  - yubico-piv-tool -r "" -a status
  - yubico-piv-tool -r "" -a test-signature -s 9e < /tmp/cert-9e.pem
  - pkcs15-tool -r 04 | openssl x509 -text | grep 'CN = CertAtSlot9e'
  - echo hello >/tmp/hello.txt
  - pkcs11-tool -d 04 -s -m SHA256-RSA-PKCS -i /tmp/hello.txt -o /tmp/hello-signed --pin 654321
  - openssl dgst -sha256 -verify /tmp/pubkey-9e.pem -signature /tmp/hello-signed /tmp/hello.txt
  - yubico-piv-tool -r "" -a verify-pin -P 222222 2>&1 | grep '2 tries left before pin is blocked.'
  - yubico-piv-tool -r "" -a verify-pin -P 222222 2>&1 | grep '1 tries left before pin is blocked.'
  - yubico-piv-tool -r "" -a verify-pin -P 222222 2>&1 | grep 'Pin code blocked'
  - yubico-piv-tool -r "" -a verify-pin -P 654321 2>&1 | grep 'Pin code blocked'
  - yubico-piv-tool -r "" -a unblock-pin -P 12345678 -N 999999 2>&1 | grep 'Successfully unblocked the pin code'
  - yubico-piv-tool -r "" -a change-puk -P 12345678 -N 87654321 2>&1 | grep 'Successfully changed the puk code'
  - yubico-piv-tool -r "" -a unblock-pin -P 87654321 -N 654321 2>&1 | grep 'Successfully unblocked the pin code'
  - yubico-piv-tool -r "" -a change-puk -P 12345678 -N 11111111 2>&1 | grep 'Failed verifying puk code, now 2 tries left before blocked'
  -
  - sudo killall pcscd || true
after_failure:
  - cat /tmp/pcscd.log
